# Generated by Django 5.2.4 on 2025-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='resturant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('BN', 'Bangladeshi'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('FF', 'Fast Food'), ('MX', 'Mexican'), ('OT', 'Other')], default='', max_length=2),
        ),
    ]
